### ISSUE TITLE
notification send "HOTWORD_PAUSE"

### ISSUE THREAD

**Issue by bugsounet** [eouia/MMM-Hotword#85]
I found a bug (again ... sorry)

AMK2 parse command HOTWORD_PAUSE by click on the mic

0|MagicMirror  | [HOTWORD] stops.
0|MagicMirror  | [HOTWORD] Final Result: { detected: false }
0|MagicMirror  | [HOTWORD] begins.
0|MagicMirror  | [HOTWORD] Detector starts listening.

there is a conversation error because hotword automatically resume on finish

its return false on the final result

line 151 (MMM-Hotword.js)
```
socketNotificationReceived: function(notification, payload) {
...
case "FINISH":
if (!payload.detected) {
 this.sendSocketNotification('RESUME')
} else {
...
```
if i disable  this.sendSocketNotification('RESUME')

AMK2 work proprely by click on the mic

**Comment by eouia** [comment]
If you are using `clicking` to activate AMK2, you don't need to use MMM-Hotword itself. 
Or you can stop MMM-Hotword by `onActivate` feature. (and to resume MMM-Hotword, you can use `onIdel` feature)

**Comment by bugsounet** [comment]
of course ! mic is using by MMM-HOTWORD
you can't use mic by hotword and AMK2 at the same time
-> AMK2 return conversation error

**Comment by Mats1978** [comment]
I'm trying to deactivate and activate MMM-HOTWORD from another Python script by using

r= requests.get "http://myip:8080/remote?action=NOTIFICATION&notification=HOTWORD_PAUSE"

and 

r= requests.get "http://myip:8080/remote?action=NOTIFICATION&notification=HOTWORD_RESUME"

(using MMM-Remote-Control)

but pausing Hotword never really worked until I found the comment from bugsounet above.

So I think I agree that "this.sendSocketNotification('RESUME')" needs to be disabled, as otherwise I was not able to pause MMM-HOTWORD with a HOTWORD_PAUSE notification.

**Comment by eouia** [comment]
@Mats1978 
I've added some fix. try to test.

**Comment by Mats1978** [comment]
Thanks yes, the new version works for me. Cheers, M

**Comment by bugsounet** [comment]
Perfect, we close the issue
